# Generated by Django 4.1.4 on 2022-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(max_length=20, verbose_name="почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="address",
            name="tel",
            field=models.CharField(max_length=30, verbose_name="номер телефона"),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="mobile",
            field=models.CharField(max_length=30),
        ),
    ]
