# Generated by Django 4.1.4 on 2023-01-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_author_book_bookspecific_producttype_publisher_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="discount_price",
        ),
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.IntegerField(default=10),
        ),
    ]
