# Generated by Django 4.1.4 on 2023-01-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0003_remove_book_discount_price_book_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="code_book",
            field=models.CharField(default=7, max_length=10, verbose_name="код товара"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="book",
                to="bookstore.author",
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="book",
                to="bookstore.category",
                verbose_name="рубрика",
            ),
        ),
        migrations.AlterField(
            model_name="bookspecificvalue",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifics",
                to="bookstore.book",
                verbose_name="Книга",
            ),
        ),
        migrations.AlterField(
            model_name="bookspecificvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specific_value",
                to="bookstore.bookspecific",
                verbose_name="Выберите из списка",
            ),
        ),
    ]
