# Generated by Django 4.1.4 on 2023-01-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookstore",
            "0004_book_code_book_alter_book_author_alter_book_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bookstore.category",
                verbose_name="рубрика",
            ),
        ),
        migrations.AlterField(
            model_name="bookspecificvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="bookstore.bookspecific",
                verbose_name="Выберите из списка",
            ),
        ),
    ]
