# Generated by Django 4.1.4 on 2023-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_title",
                    models.CharField(
                        help_text="* обязательное поле",
                        max_length=100,
                        verbose_name="метод доставки",
                    ),
                ),
                (
                    "delivery_price",
                    models.CharField(max_length=30, verbose_name="стоимость доставки"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("np", "Новая Почта"),
                            (
                                "Самовывоз из офиса",
                                (
                                    ("of_one", "Киев, ул. Крещатик, 5"),
                                    ("of_two", "Киев, ул, Бассейная, 3"),
                                ),
                            ),
                            ("up", "УкрПочта"),
                        ],
                        help_text="* обязательно",
                        max_length=255,
                        verbose_name="вариант доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция доставки",
                "verbose_name_plural": "Опции доставок",
            },
        ),
    ]
