# Generated by Django 4.1.4 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_title",
                    models.CharField(
                        help_text="* обязательное поле",
                        max_length=100,
                        verbose_name="метод доставки",
                    ),
                ),
                (
                    "delivery_price",
                    models.CharField(max_length=30, verbose_name="стоимость доставки"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("sz", "Самовывоз из офиса"),
                            ("np", "Новая Почта"),
                            ("up", "УкрПочта"),
                        ],
                        help_text="* обязательно",
                        max_length=255,
                        verbose_name="вариант доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция доставки",
                "verbose_name_plural": "Опции доставок",
            },
        ),
        migrations.CreateModel(
            name="PaymentOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_title",
                    models.CharField(
                        help_text="* обязательное поле",
                        max_length=100,
                        verbose_name="метод оплаты",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("c", "Наличными"),
                            ("ba", "Банковской картой"),
                            ("p", "На карту Приват"),
                            ("ba", "Перевод на рассчетный счет"),
                        ],
                        help_text="* обязательно",
                        max_length=255,
                        verbose_name="вариант оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция платежа",
                "verbose_name_plural": "Опции платежей",
            },
        ),
    ]
