# Generated by Django 4.1.4 on 2023-01-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_title",
                    models.CharField(
                        help_text="* обязательное поле",
                        max_length=100,
                        verbose_name="метод оплаты",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("c", "Наличными"),
                            ("ba", "Банковской картой"),
                            ("p", "На карту Приват"),
                            ("ba", "Перевод на рассчетный счет"),
                        ],
                        help_text="* обязательно",
                        max_length=255,
                        verbose_name="вариант оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция платежа",
                "verbose_name_plural": "Опции платежей",
            },
        ),
        migrations.AlterField(
            model_name="deliveryoptions",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    (
                        "Самовывоз из офиса",
                        (
                            ("of_one", "Киев, ул. Крещатик, 5"),
                            ("of_two", "Киев, ул, Бассейная, 3"),
                        ),
                    ),
                    ("np", "Новая Почта"),
                    ("up", "УкрПочта"),
                ],
                help_text="* обязательно",
                max_length=255,
                verbose_name="вариант доставки",
            ),
        ),
    ]
