# Generated by Django 4.1.4 on 2023-01-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="shipping_address",
                to="account.address",
                verbose_name="Адрес доставки",
            ),
        ),
    ]
